name: CI (Tests + Security)

on:
  push:
    branches: [ main ]

jobs:
  test_and_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t final-app:test .

      - name: Run tests
        run: docker run --rm final-app:test pytest -q

      - name: Security scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: final-app:test
          severity: CRITICAL,HIGH
          exit-code: 0
